language: python

# Python versions to be tested
python:
  - "2.7"

env:
  global:
    - PIP_INSTALL="pip install --upgrade"

before_install:
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran clang ant doxygen
  - sudo apt-get install -qq python-matplotlib 
  - sudo apt-get update -qq
  - sudo $PIP_INSTALL pip
  - sudo apt-get -qq install python-numpy python-scipy python-matplotlib python-networkx
  - $PIP_INSTALL fnss
  - cd icarus

install:
  - sudo pip install scipy
  - sudo pip install numpy
  - $PIP_INSTALL networkx
  - $PIP_INSTALL fnss


script:
  - "nosetests"