language: python

# Python versions to be tested
python:
  - "2.7"

env:
  global:
    - PIP_INSTALL="pip install --upgrade"

before_install:
  # For Ubuntu 12.04 VMs
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran clang ant doxygen
  - sudo $PIP_INSTALL pip
  # The next couple lines fix a crash with multiprocessing on Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  # For Ubuntu 14.04 VMs (when it'll be avaialable)
  # - sudo apt-get -qq install python-numpy python-scipy python-matplotlib python-networkx
  # - $PIP_INSTALL fnss

install:
  - $PIP_INSTALL networkx
  - $PIP_INSTALL fnss

script:
  - "nosetests"