language: node_js && python
python: "2.7"
install: 
node_js: "5.3"
script: npm run cover && python /icarus/test.py
after_script: npm run report
before_install:
  - cd visualization
addons:
  code_climate:
    repo_token: a7eedabcadb0a6d386326ec94f9ea7709d33c38f075b822739323a8e6d9150e6
branches:
  only:
    - master
    - six_tests
