language: python

# Python versions to be tested
python:
  - "2.7"

env:
  global:
    - PIP_INSTALL="pip install --upgrade"

before_install:
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran clang ant doxygen
  - sudo apt-get update -qq
  - sudo $PIP_INSTALL pip
  - sudo -H pip install scipy
  - sudo -H pip install numpy
  - sudo -H pip install matplotlib
  - cd icarus

install:
  - $PIP_INSTALL networkx
  - $PIP_INSTALL fnss


script:
  - "nosetests"