language: python

# Python versions to be tested
python:
  - "2.7"

env:
  global:
    - PIP_INSTALL="pip install --upgrade"

before_install:
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran clang ant doxygen
  - sudo apt-get install -qq python-numpy python-scipy
  - cd icarus


virtualenv:
  system_site_packages: true

install:
  - pip install matplotlib
  - pip install networkx 
  - pip install fnss


script:
  - "nosetests"